export const authDispatch = Object.freeze({
    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_IN_FAILED: "USER_LOGGED_IN_FAILED",

    AUTH_ERROR: "AUTH_ERROR",

    AUTH_LOADING: "AUTH_LOADING",

    USER_CREATED: "USER_CREATED",
    USER_CREATE_FAILED: "USER_CREATE_FAILED",

    SET_REDIRECT_URL: "SET_REDIRECT_URL",
} as const);
