export const authDispatch = Object.freeze({
    AUTH_ERROR: "AUTH_ERROR",
    AUTH_LOADING: "AUTH_LOADING",
    INITIAL_AUTH_SUCCESS: "INITIAL_AUTH_SUCCESS",

    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_IN_FAILED: "USER_LOGGED_IN_FAILED",

    USER_LOGGED_OUT: "USER_LOGGED_OUT",

    USER_CREATED: "USER_CREATED",
    USER_CREATE_FAILED: "USER_CREATE_FAILED",

    SET_REDIRECT_URL: "SET_REDIRECT_URL",
    RESET_REDIRECT_URL: "RESET_REDIRECT_URL",
} as const);
