export const authDispatch = Object.freeze({
    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_IN_FAILED: "USER_LOGGED_IN_FAILED",

    AUTH_ERROR: "AUTH_ERROR",

    USER_LOGGED_OUT_SUCCESS: "USER_LOGGED_OUT_SUCCESS",
    USER_LOGGED_OUT_FAILURE: "USER_LOGGED_OUT_FAILURE",

    AUTH_LOADING: "AUTH_LOADING",

    USER_CREATED: "USER_CREATED",
    USER_CREATE_FAILED: "USER_CREATE_FAILED",
} as const);
