export const authDispatch = {
    USER_LOGGED_IN_SUCCESS: "USER_LOGGED_IN_SUCCESS",
    USER_LOGGED_IN_FAILURE: "USER_LOGGED_IN_FAILURE",

    AUTH_ERROR: "AUTH_ERROR",

    USER_LOGGED_OUT_SUCCESS: "USER_LOGGED_OUT_SUCCESS",
    USER_LOGGED_OUT_FAILURE: "USER_LOGGED_OUT_FAILURE",
};
